scoopen/pythonbatch/urls.py
from django.contrib import admin
from django.urls import path
from pythonbatch import views
'''
urlpatterns = [
   
   path('admin/', admin.site.urls),
   path('show/',views.show),
   path('edit/<int:id>', views.edit),
   path('update/<int:id>', views.update),
   path('delete/<int:id>', views.destroy),
   path('stud/',views.applandingpage),
   
]
'''

scoopen/scoopen/urls.py
from django.contrib import admin
from django.urls import path,include
from pythonbatch import views
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('python/',include("pythonbatch.urls")),
    path('show/', views.show),
    path('edit/<int:econtact>', views.edit),
    path('update/<int:econtact>',views.update),
    path('delete/<int:econtact>',views.destroy),
    path('stud/', views.applandingpage),

]


scoopen/pythonbatch/models.py
from django.db import models

# Create your models here.


class Students(models.Model):
    student_id = models.IntegerField()
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    econtact = models.IntegerField()
    class Meta:
        db_table = "students"

scoopen/pythonbatch/views.py
from django.shortcuts import render, redirect
from pythonbatch.models import Students
from pythonbatch.form import StudentForm


# Create your views here.
def applandingpage(request):
    if request.method == "POST":
        sform = StudentForm(request.POST)
        if sform.is_valid(): #validation
            try:
                sform.save()
                return redirect('/show')
            except:
                pass
    else:
        sform = StudentForm()
    return render(request,'index.html',{'form':sform})


def show(request):
    studlist = Students.objects.all()
    return render(request,"show.html",{'studentlist':studlist})


def edit(request,econtact):
    studrecord = Students.objects.get(econtact=econtact)
    return render(request,'edit.html', {'singleStud':studrecord})


def update(request, econtact):
    stud = Students.objects.get(econtact = econtact)
    sform = StudentForm(request.POST, instance = stud)
    if sform.is_valid():
        sform.save()
        return redirect("/show")
    return render(request, 'edit.html', {'singleStud': stud})

def destroy(request,first_name):
    stud = Students.objects.get(first_name=first_name)
    stud.delete()
    return redirect("/show")

scoopen/pythonbatch/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{singleStud.econtact}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Id:</label>
    <div class="col-sm-4">
        <input type="text" name="student_id" id="id_student_id" required maxlength="20" value="{{ singleStud.student_id }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student FirstName:</label>
    <div class="col-sm-4">
        <input type="text" name="first_name" id="id_first_name" required maxlength="100" value="{{ singleStud.first_name }}" />
    </div>
  </div>

        <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student LastName:</label>
    <div class="col-sm-4">
        <input type="text" name="last_name" id="id_last_name" required maxlength="100" value="{{ singleStud.last_name }}" />
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Email:</label>
    <div class="col-sm-4">
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ singleStud.email }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ singleStud.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

scoopen/pythonbatch/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/stud/">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Id:</label>
    <div class="col-sm-4">
      {{ form.student_id }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">StudentFirst Name:</label>
    <div class="col-sm-4">
      {{ form.first_name }}
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Last Name:</label>
    <div class="col-sm-4">
      {{ form.last_name }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Email:</label>
    <div class="col-sm-4">
      {{ form.email }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Contact:</label>
    <div class="col-sm-4">
      {{ form.econtact }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

scoopen/pythonbatch/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Records</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Student ID</th>
        <th>Student FName</th>
        <th>Student LName</th>
        <th>Student Email</th>
        <th>Student Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for stud in studentlist %}
    <tr>
        <td>{{ stud.student_id }}</td>
        <td>{{ stud.first_name }}</td>
        <td>{{ stud.last_name }}</td>
        <td>{{ stud.email }}</td>
        <td>{{ stud.econtact }}</td>
        <td>
            <a href="/edit/{{ stud.econtact }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ stud.econtact }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/stud" class="btn btn-primary">Add New Record</a></center>
</body>
</html>